Feature backup to bot
Sairsey/manga-reader pull request #100
Opened 2022-05-07 16:45 UTC by PopovIV

2022-05-07 20:19 UTC, Sairsey requested changes

2022-05-07 20:19 UTC, Sairsey commented on src/MangaJet/app/src/main/AndroidManifest.xml
> +</manifest>
Add new line in the end of file

2022-05-07 20:19 UTC, Sairsey commented on src/MangaJet/app/src/main/java/com/mangajet/mangajet/MainActivity.kt
> +            if(report.isEmpty()) // Ask me about this later, Vova
I think I got it.. Some times report is exist but empty. It isn`t a bad thing, you just must check it at start of function.
But Archive you should create only if user wanted to create it. So move archive creation to Dialog "positive" callback

2022-05-07 20:19 UTC, Sairsey commented on src/MangaJet/app/src/main/java/com/mangajet/mangajet/game/GameActivity.kt
> +        val bitmap = resources.getDrawable(R.drawable.anime_girl).toBitmap()
Maybe we should use some pics from https://konachan.net or https://rule34.paheal.net

2022-05-07 20:19 UTC, Sairsey commented on src/MangaJet/app/src/main/res/layout/activity_game.xml
> +</FrameLayout>
Add new line at the end of file

2022-05-07 20:19 UTC, Sairsey commented on src/MangaJet/app/src/main/res/xml/filepaths.xml
> +</paths>
Add new line in the end of file. And why we need this?

2022-05-07 22:59 UTC, aVorotnikov approved these changes

2022-05-08 13:00 UTC, Sairsey approved these changes

2022-05-08 13:00 UTC, merged